info/__init__.py
import logging.handlers
from flask import Flask
from flask import g, render_template
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect, generate_csrf
from flask_session import Session
import redis
import logging
from info.utils.common import user_login_data


db = SQLAlchemy()
redis_store = None


def create_app(config_name):
    setup_log(config_name)
    app = Flask(__name__)

    app.config.from_object(config[config_name])

    db.init_app(app)
    # 配置redis
    global redis_store
    redis_store = redis.StrictRedis(host=config[config_name].REDIS_HOST, port=config[config_name].REDIS_PORT,
                                    decode_responses=True)
    # 开启csrf保护
    CSRFProtect(app)
    # 设置session保存位置
    Session(app)

    @app.after_request
    def after_request(response):
        csrf_token = generate_csrf()
        response.set_cookie('csrf_token', csrf_token)
        return response

    # 注册蓝图 首页
    from info.modules.index import index_blu
    app.register_blueprint(index_blu)
    # 登陆注册模块
    from info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)
    # 装饰器
    from info.utils.common import do_index_class
    app.add_template_filter(do_index_class, "indexClass")
    # 新闻详情
    from info.modules.news import news_blu
    app.register_blueprint(news_blu)
    # 个人中心
    from info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)
    # 后台管理
    from info.modules.admin import admin_blu
    app.register_blueprint(admin_blu)

    @app.errorhandler(404)
    @user_login_data
    def page_not_found(e):
        data = {
            "user_info": g.user.to_dict() if g.user else None
        }
        return render_template("news/404.html", data=data)
    return app


def setup_log(config_name):
    # 设置日志的记录等级
    logging.basicConfig(level=config[config_name].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = logging.handlers.RotatingFileHandler("logs/logs", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

info/modules/admin/__init__.py
from flask import Blueprint, url_for
from flask import session, redirect, request
from info import user_login_data

admin_blu = Blueprint('admin', __name__, url_prefix="/admin")

from . import views


@admin_blu.before_request
@user_login_data
def before_request():

    if not request.url.endswith(url_for("admin.admin_login")):
        user_id = session.get("user_id", None)
        is_admin = session.get("is_admin", False)
        if (not user_id) or (not is_admin):
            return redirect("/")

info/modules/admin/views.py
import datetime
import time
from info.utils.response_code import RET
from datetime import timedelta, datetime
from flask import session, g
from flask import current_app, redirect, url_for
from flask import request
from flask import render_template, jsonify
from info import constants, db
from info import user_login_data
from info.models import User, News, Category
from info.modules.admin import admin_blu
from info.utils.image_storage import storage


@admin_blu.route("/login", methods=["GET", "POST"])
@user_login_data
def admin_login():
    if request.method == "GET":
        user_id = session.get("user_id", None)
        is_admin = session.get("is_admin", False)
        if user_id and is_admin:
            return redirect(url_for("admin.admin_index"))
        return render_template("admin/login.html")
    username = request.form.get("username")
    password = request.form.get("password")
    if not all([username, password]):
        return render_template("admin/login.html", errmsg="参数不足")

    try:
        users = User.query.filter(User.mobile == username).first()
    except Exception as e:
        current_app.logger.error(e)
        return render_template("admin/login.html", errmsg="查询错误")

    if not users:
        return render_template("admin/login.html", errmsg="用户不存在")

    if not users.check_password(password):
        return render_template("admin/login.html", errmsg="密码错误")

    if not users.is_admin:
        return render_template("admin/login.html", errmsg="用户权限错误")

    session["user_id"] = users.id
    session["nick_name"] = users.nick_name
    session["mobile"] = users.mobile
    session["is_admin"] = True

    return redirect(url_for("admin.admin_index"))


@admin_blu.route("/index")
@user_login_data
def admin_index():
    user = g.user
    return render_template("admin/index.html", user=user.to_dict())


@admin_blu.route('/user_count')
def user_count():
    # 查询总人数
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    # 查询月新增数
    mon_count = 0
    try:
        now = time.localtime()
        mon_begin = '%d-%02d-01' % (now.tm_year, now.tm_mon)
        mon_begin_date = datetime.strptime(mon_begin, "%Y-%m-%d")
        mon_count = User.query.filter(User.is_admin == False, User.create_time >= mon_begin_date).count()
    except Exception as e:
        current_app.logger.error(e)
    # 查询日新增数
    day_count = 0
    try:
        day_begin = "%d-%02d-%02d" % (now.tm_year, now.tm_mon, now.tm_mday)
        day_begin_date = datetime.strptime(day_begin, "%Y-%m-%d")
        day_count = User.query.filter(User.is_admin == False, User.create_time >= day_begin_date).count()
    except Exception as e:
        current_app.logger.error(e)

    # 查询图表信息
    # 获取到当天00:00:00时间
    now_date = datetime.strptime(datetime.now().strftime("%Y-%m-%d"), "%Y-%m-%d")

    # 定义空数组，保存数据
    active_date = []
    active_count = []

    # 依次添加数据，再反转

    for i in range(0, 31):
        begin_date = now_date - timedelta(days=i)
        end_date = now_date + timedelta(days=1)
        active_date.append(begin_date.strftime("%Y-%m-%d"))
        count = 0
        try:
            count = User.query.filter(User.is_admin == False, User.last_login >= day_begin,
                                      User.last_login < end_date).count()
        except Exception as e:
            current_app.logger.error(e)

        active_count.append(count)

    active_count.reverse()
    active_date.reverse()

    data = {
        "total_count": total_count,
        "mon_count": mon_count,
        "day_count": day_count,
        "active_date": active_date,
        "active_count": active_count
    }
    return render_template("admin/user_count.html", data=data)


@admin_blu.route("/user_list")
def user_list():
    """获取用户列表"""
    page = request.args.get("p", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    collections = []
    current_page = 1
    total_page = 1

    try:
        # 进行分页数据查询

        paginate = User.query.filter(User.is_admin == False) \
            .order_by(User.last_login.desc()) \
            .paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        # 获取分页数据
        collections = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    # 收藏列表
    collection_dict_list = []
    for user in collections:
        collection_dict_list.append(user.to_admin_dict())

    data = {
        "total_page": total_page,
        "current_page": current_page,
        "users": collection_dict_list
    }

    return render_template("admin/user_list.html", data=data)


@admin_blu.route("/news_review")
def news_review():
    """返回待审核新闻列表"""
    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", "")
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    collections = []
    current_page = 1
    total_page = 1

    try:
        # 进行分页数据查询
        filters = [News.status != 0]
        if keywords:
            filters.append(News.contains(keywords))

        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()). \
            paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)
        # 获取分页数据
        collections = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    # 列表
    collection_dict_list = []
    for news in collections:
        collection_dict_list.append(news.to_review_dict())

    data = {
        "total_page": total_page,
        "current_page": current_page,
        "news_list": collection_dict_list
    }

    return render_template("admin/news_review.html", data=data)


@admin_blu.route("/news_review_detail")
def news_review_detail():
    """新闻审核"""
    # if request.method == "GET":
    news_id = request.args.get("news_id")
    if not news_id:
        return render_template("admin/news_review_detail.html", data={"errmsg": "未查询到此新闻"})
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    if not news:
        return render_template("admin/news_review_detail.html", data={"errmsg": "未查询到此新闻"})

    data = {
        "news": news.to_dict()
    }
    return render_template("admin/news_review_detail.html", data=data)


@admin_blu.route("/news_review_add", methods=["POST"])
def news_review_add():
    news_id = request.json.get("news_id")
    action = request.json.get("action")

    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    if action not in ("accept", "reject"):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到数据")

    if action == "accept":
        news.status = 0
    else:
        reason = request.json.get("reason")

        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

        news.reason = reason
        news.status = -1

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="数据保存失败")
    return jsonify(errno=RET.OK, errmsg="操作成功")


@admin_blu.route("/news_edit")
def news_edit():
    # 新闻编辑
    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", "")
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    collections = []
    current_page = 1
    total_page = 1

    try:
        # 进行分页数据查询
        filters = [News.status != 0]
        if keywords:
            filters.append(News.contains(keywords))

        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()). \
            paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)
        # 获取分页数据
        collections = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    # 收藏列表
    collection_dict_list = []
    for news in collections:
        collection_dict_list.append(news.to_review_dict())

    data = {
        "total_page": total_page,
        "current_page": current_page,
        "news_list": collection_dict_list
    }
    return render_template("admin/news_edit.html", data=data)


@admin_blu.route("/news_edit_detail", methods=["GET", "POST"])
def news_edit_detail():
    """新闻编辑详情"""
    if request.method == "GET":
        news_id = request.args.get("news_id")
        if not news_id:
            return render_template("admin/news_edit_detail.html", data={"errmsg": "未查询到此新闻"})
        news = None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)

        if not news:
            return render_template("admin/news_edit_detail.html", data={"errmsg": "未查询到此新闻"})

        categories = Category.query.all()
        categories_li = []
        for category in categories:
            c_dict = category.to_dict()
            c_dict["is_selected"] = False
            if category.id == news.category_id:
                c_dict["is_selected"] = True
            categories_li.append(c_dict)

        categories_li.pop(0)

        data = {
            "news": news.to_dict(),
            "categories": categories_li
        }
        return render_template("admin/news_edit_detail.html", data=data)
        # 获取参数
    news_id = request.form.get("news_id")
    title = request.form.get("title")

info/modules/index/__init__.py
from flask import Blueprint

index_blu = Blueprint('index', __name__)

from . import views

info/modules/index/views.py
import info.constants
import info.utils.common
from info.models import News, Category, User
from info.utils.response_code import RET
from . import index_blu
from flask import render_template, jsonify
from flask import current_app
from flask import session, request, g
from info.utils.common import user_login_data, news_list_click


@index_blu.route("/newslist")
def news_list():
    """
    获取指定分类的新闻列表
    1. 获取参数
    2. 校验参数
    3. 查询数据
    4. 返回数据
    :return:
    """
    # 1.获取参数
    args_dict = request.args
    page = args_dict.get("page", "1")
    per_page = args_dict.get("per_page", 10)
    category_id = args_dict.get("cid", "1")
    # 校验参数
    try:
        page = int(page)
        category_id = int(category_id)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    # 3. 查询数据并分页

    filters = [News.status == 0]
    # 如果分类id不为1，那么添加分类id的过滤
    if category_id != 1:
        # print(category_id)
        filters.append(info.models.News.category_id == category_id)
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)

        # 获取查询出来的数据
        items = paginate.items

        # 获取到总页数
        total_page = paginate.pages

        current_page = paginate.page

    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询失败")

    news_li = []
    for news in items:
        news_li.append(news.to_basic_dict())
    # 4. 返回数据
    return jsonify(errno=RET.OK, errmsg="OK", totalPage=total_page, currentPage=current_page, newsList=news_li,
                   cid=category_id)


@index_blu.route("/")
@user_login_data
@news_list_click
def index():
    # 新闻排行

    # 获取新闻分类数据
    categories = Category.query.all()
    # 定义列表保存分类数据
    categories_dicts = []

    for category in categories:
        # 拼接内容
        categories_dicts.append(category.to_dict())

    data = {
        "user_info": g.user.to_dict() if g.user else None,
        "click_news_list": g.click_news_list,
        "categories": categories_dicts
    }
    return render_template('news/index.html', data=data)


@index_blu.route('/favicon.ico')
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/modules/news/__init__.py
from flask import Blueprint

news_blu = Blueprint('news', __name__, url_prefix="/news")

from . import views

info/modules/passport/__init__.py
from flask import Blueprint

passport_blu = Blueprint("passport", __name__, url_prefix="/passport")

from . import views

info/modules/profile/__init__.py
from flask import Blueprint

profile_blu = Blueprint("profile", __name__, url_prefix="/user")

from . import views

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %}

    {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block script_block %}

    {% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        {% block  category_block %}
            <ul class="menu fl">
                {% for category in data.categories %}
                    {% if loop.index == 1 %}
                        <li data-cid="{{ category.id }}" class="active"><a href="javascript:;">{{ category.name }}</a>
                        </li>
                    {% else %}
                        <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endblock %}

        {% if data.user_info %}
            <!-- 用户登录后显示下面，隐藏上面 -->
            <div class="user_login fr">
                <img src="{% if data.user_info.avatar_url %} {{ data.user_info.avatar_url }} {% else %}../../static/news/images/person01.png{% endif %}"
                     class="lgin_pic">
                <a id="nick_name" href="/user/info">{{ data.user_info.nick_name }}</a>
                <a href="/" onclick="logout()">退出</a>
            </div>
        {% else %}
            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
        {% endif %}
    </div>
</div>

<div class="conter_con">
    {% block content_block %}

    {% endblock %}
    <div class="rank_con fr">
        {% block autor_block %}

        {% endblock %}
        {% block rank_block %}
        <div class="rank_title">
            <h3>点击排行</h3>
        </div>
        <ul class="rank_list">
            {% for news in data.click_news_list %}
                <li><span class="{{ loop.index0 | indexClass }}">{{ loop.index }}</span><a
                        href="/news/{{ news.id }}">{{ news.title }}</a>
                </li>
            {% endfor %}
        </ul>
        {% endblock %}
    </div>
</div>
{% block bottomBlock %}
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>
{% endblock %}
<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input id="mobile" type="text" name="mobile" autocomplete="off">
            <div class="input_tip">手机号</div>
            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">
    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
            <div class="input_tip">手机号</div>
            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">手机验证码</div>
            <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>
</body>
</html>

info/templates/news/detail.html
{% extends "news/base.html" %}
{% block title_block %}
    文章详情页
{% endblock %}

{% block script_block %}
    <script type="text/javascript" src="../../static/news/js/detail.js"></script>
{% endblock %}

{% block content_block %}
    <div class="detail_con fl">
        <h3>{{ data.news.title }}</h3>
        <div class="detail_about clearfix">
            <span class="time_souce fl">{{ data.news.create_time }} 来源: {{ data.news.source }}</span>
            <span class="comment fr">{{ data.news.comments_count }}</span>
        </div>
        {{ data.news.content | safe }}

        <a href="javascript:;" class="collected block-center" data-newid="{{ data.news.id }}"
           style="display: {% if data.is_collected %} block
           {% else %} none {% endif %};"><span class="out">已收藏</span><span class="over">取消收藏</span></a>
        <a href="javascript:;" class="collection block-center" data-newid="{{ data.news.id }}"
           style="display: {% if data.is_collected %} none
           {% else %} block {% endif %};">收藏</a>


        {% if data.user_info %}
            <form action="" class="comment_form" data-newsid="{{ data.news.id }}">
                <div class="person_pic">
                    <img src="{% if data.user_info.avatar_url %}
                    {{ data.user_info.avatar_url }}
                {% else %}
                    ../../static/news/images/person01.png
                {% endif %}" alt="用户图标">
                </div>
                <textarea placeholder="请发表您的评论" class="comment_input"></textarea>
                <input type="submit" name="" value="评 论" class="comment_sub">
            </form>
        {% else %}
            <div class="comment_form_logout">
                {{ data.news.comments_count }}条评论
            </div>
        {% endif %}


        <div class="comment_count">
            {{ data.news.comments_count }}条评论
        </div>

        <div class="comment_list_con">
            {% for comment in data.comments %}
                <div class="comment_list">
                    <div class="person_pic fl">
                        <img src="{% if comment.user.avatar_url %}
                {{ comment.user.avatar_url }}
            {% else %}
                ../../static/news/images/person01.png
            {% endif %}" alt="用户图标">
                    </div>
                    <div class="user_name fl">{{ comment.user.nick_name }}</div>
                    <div class="comment_text fl">{{ comment.content }}</div>
                    {% if comment.parent %}
                        <div class="reply_text_con fl">
                            <div class="user_name2">{{ comment.parent.user.nick_name }}</div>
                            <div class="reply_text">
                                {{ comment.parent.content }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="comment_time fl">{{ comment.create_time }}</div>
                    <a href="javascript:;" class="comment_up
                        {% if comment.is_like %}
                        has_comment_up
                        {% endif %} fr"
                        data-commentid="{{ comment.id }}"
                        data-likecount="{{ comment.like_count }}"
                        data-newsid="{{ data.news.id }}">
                        {% if comment.like_count > 0 %}
                            {{ comment.like_count }}
                        {% else %}
                            赞
                        {% endif %}</a>

                    <a href="javascript:;" class="comment_reply fr">回复</a>
                    <form class="reply_form fl" data-commentid="{{ comment.id }}" data-newsid="{{ data.news.id }}">
                        <textarea class="reply_input"></textarea>
                        <input type="button" value="回复" class="reply_sub fr">
                        <input type="reset" name="" value="取消" class="reply_cancel fr">
                    </form>
                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}
{% block category_block %}

{% endblock %}

{% block autor_block %}
     {% if data.news.author %}
        <div class="author_card">
            <a href="#" class="author_pic"><img src="{% if data.news.author.avatar_url %}
            {{ data.news.author.avatar_url }}
            {% else %}
            ../../static/news/images/user_pic.png
            {% endif %}" alt="author_pic"></a>
            <a href="#" class="author_name">{{ data.news.author.nick_name }}</a>
            <div class="author_resume">签名：{{ data.news.author.signature }}</div>
            <div class="writings"><span>总篇数</span><b>{{ data.news.author.news_count }}</b></div>
            <div class="follows"><span>粉丝</span><b>{{ data.news.author.followers_count }}</b></div>
            <a href="javascript:;" class="focus fr" data-userid="{{ data.news.author.id }}" style="display: {% if data.is_followed %}none{% else %}block{% endif %}">关注</a>
            <a href="javascript:;" class="focused fr" data-userid="{{ data.news.author.id }}" style="display: {% if data.is_followed %}block{% else %}none{% endif %}"><span class="out">已关注</span><span class="over">取消关注</span></a>
        </div>
    {% endif %}
{% endblock %}

info/templates/news/index.html
{% extends "news/base.html" %}
{% block title_block %}
    首页-新经资讯
{% endblock %}

{% block script_block %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block content_block %}
    <ul class="list_con fl"></ul>
{% endblock %}

{% block autor_block %}

{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}
{% block title_block %}
    用户中心
{% endblock %}

{% block script_block %}
    <script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}

{% block content_block %}
<div class="user_menu_con fl">
    <div class="user_center_pic">
        <img src={% if data.user_info.avatar_url %}
            {{ data.user_info.avatar_url }}
        {% else %}
            "../../static/news/images/user_pic.png"
        {% endif %} alt="用户图片">
    </div>
    <div class="user_center_name">{{ data.user_info.nick_name }}</div>

    <ul class="option_list">
        <li class="active"><a href="{{ url_for("profile.base_info") }}" target="main_frame">基本资料</a></li>
        <li><a href="{{ url_for("profile.pic_info") }}" target="main_frame">头像设置</a></li>
        <li><a href="{{ url_for("profile.user_follow") }}" target="main_frame">我的关注</a></li>
        <li><a href="{{ url_for("profile.pass_info") }}" target="main_frame">密码修改</a></li>
        <li><a href="{{ url_for("profile.user_collection") }}" target="main_frame">我的收藏</a></li>
        <li><a href="{{ url_for("profile.news_release") }}" target="main_frame">新闻发布</a></li>
        <li><a href="{{ url_for("profile.news_list")}}" target="main_frame">新闻列表</a></li>
    </ul>
</div>

<div class="user_con fr">
    <iframe src="{{ url_for("profile.base_info") }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
</div>
{% endblock %}

{% block rank_block %}
{#重写rankBlock，内部什么什么都不填#}
{% endblock %}